runtime: nodejs16 # or another supported version

instance_class: F2

#env_variables:
#  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$

- url: /.*
  static_files: build/index.html
  upload: build/index.html